url: https://joosthoeks.github.io/blog
title: Joost Hoeks Blog
author: Joost Hoeks
email: joosthoeks@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  As melhores coisas da vida são de graça...

# social links
#twitter_username: jekyll
github_username:  joosthoeks
telegram_username: joosthoeks
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
#mastodon:
# - username: jekyll
#   instance: jekyll


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
    #  date_format: "%b %-d, %Y"
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# - blog.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag


